jobs:
  build:
    defaults:
      run:
        working-directory: android_app
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Build APK
      run: ./gradlew assembleDebug
    - continue-on-error: true
      uses: marvinpinto/action-automatic-releases@latest
      with:
        automatic_release_tag: dev-build
        files: 'android_app/app/build/outputs/apk/debug/openScale-debug.apk

          '
        prerelease: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        title: openScale development build
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
